# Generated by Django 5.2.7 on 2025-10-13 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('rating', models.FloatField(help_text='Note entre 0 et 5.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Hiatus', 'Hiatus')], default='En cours', max_length=20)),
                ('chapter', models.PositiveIntegerField(help_text='Dernier chapitre lu.')),
                ('link', models.URLField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'webtoon',
                'verbose_name_plural': 'webtoons',
                'ordering': ('-last_update', 'title'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_comments', to=settings.AUTH_USER_MODEL)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.webtoon')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.webtoon')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ('webtoon', 'chapter_number'),
                'abstract': False,
                'unique_together': {('webtoon', 'chapter_number')},
            },
        ),
    ]
