# Generated by Django 5.2.7 on 2025-10-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_webtoon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='local_folder',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chapter',
            name='local_image_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
