# Generated by Django 5.0.6 on 2025-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="last_chapter",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
